### ISSUE TITLE
페이지별 보기 오류 현상

### ISSUE THREAD

**Issue by okaybody10** [fractalo/twitch-chat-nexus#2]
- 현재 설정을 페이지별 보기로 하여 설정을 한 후 다음을 누르는 식으로 chat history를 보고자 하면, 불러오는 중에 예상하지 못한 오류가 발생했다며, 나중에 다시 시도해달라는 문구가 뜨고 있습니다.
- ![image](https://github.com/fractalo/twitch-chat-history/assets/97182875/0e1d0789-f9df-4ca4-afc9-466f7781d47d)
- Network를 보았을 때 불러오는거 자체는 큰 문제가 없는데 아마 이거를 웹페이지에 보여주는 과정에서 오류가 발생한 것 같은데, 혹시 확인해 주실 수 있을까해서 issue 올립니다.

**Comment by fractalo** [comment]
제보 감사합니다!
GQL 쿼리에 추가된 필드가 있어서 발생하는 이슈였고, 1.1.6 버전에서 문제가 수정되었습니다.

**Comment by okaybody10** [comment]
@fractalo 안녕하세요! 혹시 1.1.6 version이 패치된거 같은데, 해당 버전은 minor 이라 추후 1.1.7과 병합이 되는건가요?
1.1.6을 따로 다운받아서 등록하여 사용하고자 하였는데 따로 개발자모드로 등록하니 error가 나서, 혹시 등록하는데 따로 설정이 필요한건지도 알고 싶습니다.

**Comment by fractalo** [comment]
> @fractalo 안녕하세요! 혹시 1.1.6 version이 패치된거 같은데, 해당 버전은 minor 이라 추후 1.1.7과 병합이 되는건가요? 1.1.6을 따로 다운받아서 등록하여 사용하고자 하였는데 따로 개발자모드로 등록하니 error가 나서, 혹시 등록하는데 따로 설정이 필요한건지도 알고 싶습니다.

추후에 병합되는건 아니고,
아직 1.1.6 버전이 심사중이여서 업데이트가 배포되지 않고 있습니다.

1.1.6 릴리즈에 빌드한 파일을 추가했으니, (https://github.com/fractalo/twitch-chat-history/releases/tag/v1.1.6)
압축 해제 후, 압축 해제한 폴더를 개발자모드에서 로드하면 사용할 수 있습니다.

또는 소스코드를 직접 빌드해서 사용하려면, 
`npm install`  후에  `npm run build` 로 빌드 후 생성되는 `dist` 폴더를 로드하면 됩니다.

**Comment by okaybody10** [comment]
> > @fractalo 안녕하세요! 혹시 1.1.6 version이 패치된거 같은데, 해당 버전은 minor 이라 추후 1.1.7과 병합이 되는건가요? 1.1.6을 따로 다운받아서 등록하여 사용하고자 하였는데 따로 개발자모드로 등록하니 error가 나서, 혹시 등록하는데 따로 설정이 필요한건지도 알고 싶습니다.
> 
> 추후에 병합되는건 아니고, 아직 1.1.6 버전이 심사중이여서 업데이트가 배포되지 않고 있습니다.
> 
> 1.1.6 릴리즈에 빌드한 파일을 추가했으니, (https://github.com/fractalo/twitch-chat-history/releases/tag/v1.1.6) 압축 해제 후, 압축 해제한 폴더를 개발자모드에서 로드하면 사용할 수 있습니다.
> 
> 또는 소스코드를 직접 빌드해서 사용하려면, `npm install` 후에 `npm run build` 로 빌드 후 생성되는 `dist` 폴더를 로드하면 됩니다.

친절한 답변 감사합니다. 해당 확장 프로그램 너무나 잘 쓰고 있습니다. 감사합니다!! 건승하세요.
