### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by NameIsNotAvailablePleaseChooseAnother** [fractalo/twitch-chat-nexus#3]
24 hours ago, this was working fine.  As of 8 hours ago, it is no longer working.

I'm using Chrome, it was working before the most recent chrome update - I had not restarted my browser since it was last working, so it wasn't a Chrome update that broke it.  Today I restarted Chrome and I also checked Firefox, and it's not working there either.

So I suspect there has been another twitch API update.

Hopefully the extension can simply be updated and can work again, but I fear that twitch has probably removed access to your own chat history now.

I have a bad memory, I use this extension on a daily basis to let me check when I was last in a stream, or which raid brought me there in the first place, so I really hope it's not dead.

**Comment by fractalo** [comment]
Thank you for reporting the error.
There were some changes in the Twitch API, and the problem was resolved in version 2.0.4.
thank you
